# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 21:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RelatedResource1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RelatedResource2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('related_resources_1', models.ManyToManyField(to='testproject.RelatedResource1')),
            ],
        ),
        migrations.CreateModel(
            name='RelatedResource3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('related_resource_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testproject.RelatedResource1')),
                ('related_resource_2', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='testproject.RelatedResource2')),
            ],
        ),
        migrations.AddField(
            model_name='customresource',
            name='related_resource_3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testproject.RelatedResource3'),
        ),
    ]
